apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: globomantics-prod

resources:
- ../../base/namespaces/
- ../../base/network-policies/
- ../../base/rbac/
- ../../base/resource-management/

patches:
- path: namespace-patch.yaml
  target:
    kind: Namespace
- path: quota-patch.yaml
  target:
    kind: ResourceQuota
- path: limit-range-patch.yaml
  target:
    kind: LimitRange
- path: default-deny-patch.yaml
  target:
    kind: NetworkPolicy
    name: default-deny-all
- path: allow-internal-patch.yaml
  target:
    kind: NetworkPolicy
    name: allow-internal-communication
- path: serviceaccount-patch.yaml
  target:
    kind: ServiceAccount
- path: role-patch.yaml
  target:
    kind: Role
- path: rolebinding-patch.yaml
  target:
    kind: RoleBinding 