apiVersion: v1
kind: LimitRange
metadata:
  name: globomantics-limits
  namespace: globomantics-prod
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 1Gi
    defaultRequest:
      cpu: 200m
      memory: 256Mi
    type: Container