apiVersion: v1
kind: ResourceQuota
metadata:
  name: globomantics-quota
  namespace: globomantics-prod
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "20"
    pods: "50"
    services: "15"