apiVersion: v1
kind: LimitRange
metadata:
  name: globomantics-limits
  namespace: globomantics-dev
spec:
  limits:
  - default:
      cpu: 100m
      memory: 128Mi
    defaultRequest:
      cpu: 25m
      memory: 32Mi
    type: Container 