apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- path: serviceaccount-patch.yaml
  target:
    kind: ServiceAccount
- path: role-patch.yaml
  target:
    kind: Role
- path: rolebinding-patch.yaml
  target:
    kind: RoleBinding